### ISSUE TITLE
✨ Add ::selection to classes

### ISSUE THREAD

**Issue by killianogorman** [darkmagicstudio/magic-selection#1]
Add `data-selection-class-e="class-name"` to add 
``` CSS
.[class-name]::selection {
background: ;
color: ;
}
```
